# These are supported funding model platforms

github: GZYangKui
patreon: GZYangKui
open_collective: GZYangKui
ko_fi: GZYangKui
tidelift: Java/maven
community_bridge: GZYangKui
liberapay: GZYangKui
issuehunt: GZYangKui
otechie: GZYangKui
custom: https://www.paypal.me/dbfx436
