# These are supported funding model platforms
github: [GZYangKui]
patreon: #
open_collective: databasefx
ko_fi: # Replace with a single Ko-fi username
tidelift: #
custom: # Replace with a single custom sponsorship URL
